site_name: Mi Configuración de ArchLinux

nav:
    - Presentación: index.md
    - Configuración: configuracion.md
    - Terminal: terminal.md

theme:
    name: dracula

extra_css:
  - css/fab.css

extra_javascript:
  - javascript/fab.js
