site_name: Mi Configuración de ArchLinux

nav:
    - Índice: index.md
    - Presentación: doc/presentacion.md
    - Configuración: doc/configuracion.md
    - Terminal: doc/terminal.md

theme:
    name: dracula

extra_css:
  - css/fab.css

extra_javascript:
  - javascript/fab.js
