site_name: Mi Documentación de ArchLinux

nav:
    - Índice: index.md
    - Presentación: presentacion.md
    - Configuración: configuracion.md
    - Terminal: terminal.md
    - Errores: errores.md

theme:
    name: material
    palette:
      - scheme: slate

    features:
      - navigation.top
